"""Async PostgreSQL access - SQLAlchemy 2.0 + asyncpg.

Engines are lazily built and cached per DSN (same idiom as
``app/rag/vector_store.py``'s ``get_vector_store(settings)``), not a single
global singleton - the test suite runs against the same server but a
different ``postgres_db`` (see ``tests/conftest.py``), so the cache key has
to be settings-derived rather than process-wide.

Usage::

    from app.core import db

    async def get_connection(settings = Depends(get_settings_dep)):
        async with db.connection(settings) as conn:
            yield conn

There is no app-layer auth: Postgres enforces its own user/password and the
port is bound to ``127.0.0.1`` only (docker-compose.yml).
"""
from __future__ import annotations

from collections.abc import AsyncIterator
from contextlib import asynccontextmanager

from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncConnection, AsyncEngine, create_async_engine

from ..config import Settings
from .logging import get_logger

_log = get_logger("app.db")

_engines: dict[str, AsyncEngine] = {}


def get_engine(settings: Settings) -> AsyncEngine:
    """The pooled engine for ``settings``' DSN, building it on first use."""
    dsn = settings.sqlalchemy_dsn()
    engine = _engines.get(dsn)
    if engine is None:
        engine = create_async_engine(
            dsn,
            pool_size=settings.db_pool_size,          # persistent connections
            max_overflow=settings.db_max_overflow,    # burst capacity above pool_size
            pool_timeout=settings.db_pool_timeout,    # seconds to wait for a free conn
            pool_recycle=settings.db_pool_recycle,    # drop conns older than this (s)
            pool_pre_ping=True,                       # detect dead conns before use
            echo=settings.db_echo,
            connect_args={
                "timeout": 10,                        # connect timeout (s)
                "command_timeout": 30,                # per-statement timeout (s)
                "server_settings": {
                    "application_name": "orchard-api",
                    "jit": "off",                     # OLTP workload: JIT hurts
                },
            },
        )
        _engines[dsn] = engine
        _log.info("db.engine.created", dsn_host=settings.postgres_host, db=settings.postgres_db)
    return engine


@asynccontextmanager
async def connection(settings: Settings) -> AsyncIterator[AsyncConnection]:
    """A unit-of-work connection: commits on clean exit, rolls back on exception."""
    async with get_engine(settings).begin() as conn:
        yield conn


# Additive, idempotent DDL applied on startup so an existing Postgres volume
# picks up columns added after its init.sql first ran (there is no migration
# tool; a full schema change still needs `docker compose down -v`). This is the
# Postgres equivalent of the old sqlite `_backfill_columns`.
_STARTUP_DDL: tuple[str, ...] = (
    "ALTER TABLE tree_sources ADD COLUMN IF NOT EXISTS priority_order INT NOT NULL DEFAULT 0",
    "CREATE INDEX IF NOT EXISTS idx_tree_sources_priority ON tree_sources (tree_id, priority_order)",
    # zones moved to Rachio: drop the FK + local table, tree.zone_id -> text
    "ALTER TABLE tree DROP CONSTRAINT IF EXISTS tree_zone_id_fkey",
    "ALTER TABLE tree ALTER COLUMN zone_id TYPE text USING zone_id::text",
    "DROP TABLE IF EXISTS zone CASCADE",
    # assistant chat history (server-owned conversation threads)
    (
        "CREATE TABLE IF NOT EXISTS conversation ("
        " id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
        " title TEXT NOT NULL DEFAULT 'New conversation',"
        " created_at TIMESTAMPTZ NOT NULL DEFAULT now(),"
        " updated_at TIMESTAMPTZ NOT NULL DEFAULT now())"
    ),
    (
        "CREATE TABLE IF NOT EXISTS chat_message ("
        " id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
        " conversation_id BIGINT NOT NULL REFERENCES conversation(id) ON DELETE CASCADE,"
        " role TEXT NOT NULL,"
        " content TEXT NOT NULL DEFAULT '',"
        " meta JSONB NOT NULL DEFAULT '{}'::jsonb,"
        " created_at TIMESTAMPTZ NOT NULL DEFAULT now())"
    ),
    "CREATE INDEX IF NOT EXISTS idx_chat_message_conversation ON chat_message (conversation_id, id)",
    # Care Plan engine: tree canopy dimensions, per-tree task templates
    "ALTER TABLE tree ADD COLUMN IF NOT EXISTS height_m NUMERIC(4,2)",
    "ALTER TABLE tree ADD COLUMN IF NOT EXISTS canopy_spread_m NUMERIC(4,2)",
    "ALTER TABLE tree ADD COLUMN IF NOT EXISTS expected_flowering_month SMALLINT",
    "ALTER TABLE tree ADD COLUMN IF NOT EXISTS expected_harvest_month SMALLINT",
    "ALTER TABLE tree ADD COLUMN IF NOT EXISTS expected_dormancy_month SMALLINT",
    "ALTER TABLE tree ADD COLUMN IF NOT EXISTS expected_flowering_months JSONB NOT NULL DEFAULT '[]'::jsonb",
    "ALTER TABLE tree ADD COLUMN IF NOT EXISTS expected_harvest_months JSONB NOT NULL DEFAULT '[]'::jsonb",
    "ALTER TABLE tree ADD COLUMN IF NOT EXISTS expected_dormancy_months JSONB NOT NULL DEFAULT '[]'::jsonb",
    "UPDATE tree SET expected_flowering_months = jsonb_build_array(expected_flowering_month) WHERE expected_flowering_month IS NOT NULL AND (expected_flowering_months = '[]'::jsonb OR expected_flowering_months IS NULL)",
    "UPDATE tree SET expected_harvest_months = jsonb_build_array(expected_harvest_month) WHERE expected_harvest_month IS NOT NULL AND (expected_harvest_months = '[]'::jsonb OR expected_harvest_months IS NULL)",
    "UPDATE tree SET expected_dormancy_months = jsonb_build_array(expected_dormancy_month) WHERE expected_dormancy_month IS NOT NULL AND (expected_dormancy_months = '[]'::jsonb OR expected_dormancy_months IS NULL)",
    (
        "CREATE TABLE IF NOT EXISTS task_templates ("
        " id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
        " tree_id BIGINT NOT NULL REFERENCES tree(tree_id) ON DELETE CASCADE,"
        " name TEXT NOT NULL,"
        " category TEXT NOT NULL,"
        " rate_class TEXT NOT NULL DEFAULT 'standard',"
        " interval_days INTEGER NOT NULL,"
        " estimated_minutes INTEGER NOT NULL,"
        " priority_score DOUBLE PRECISION NOT NULL DEFAULT 5.0,"
        " required_resources JSONB NOT NULL DEFAULT '[]'::jsonb,"
        " resource_plan JSONB NOT NULL DEFAULT '[]'::jsonb,"
        " baseline_question TEXT,"
        " anchor_date DATE,"
        " source_ids JSONB NOT NULL DEFAULT '[]'::jsonb,"
        " created_at TIMESTAMPTZ NOT NULL DEFAULT now(),"
        " updated_at TIMESTAMPTZ NOT NULL DEFAULT now())"
    ),
    "CREATE INDEX IF NOT EXISTS idx_task_templates_tree ON task_templates (tree_id)",
    "ALTER TABLE task ADD COLUMN IF NOT EXISTS template_id BIGINT REFERENCES task_templates(id) ON DELETE SET NULL",
    "CREATE INDEX IF NOT EXISTS idx_task_template ON task (template_id) WHERE template_id IS NOT NULL",
    "ALTER TABLE task_templates ADD COLUMN IF NOT EXISTS valid_months JSONB NOT NULL DEFAULT '[]'::jsonb",
    "ALTER TABLE task_templates ADD COLUMN IF NOT EXISTS biological_anchor TEXT",
    "ALTER TABLE task_templates ADD COLUMN IF NOT EXISTS anchor_offset_days INTEGER",
    "ALTER TABLE task_templates ADD COLUMN IF NOT EXISTS blocks JSONB NOT NULL DEFAULT '[]'::jsonb",
    # widen the task status enum: + 'skipped'
    "ALTER TABLE task DROP CONSTRAINT IF EXISTS task_status_check",
    "ALTER TABLE task ADD CONSTRAINT task_status_check CHECK (status IN ('pending', 'completed', 'deferred', 'skipped'))",
    # Irrigation workflow (Phase 1)
    "ALTER TABLE tree ADD COLUMN IF NOT EXISTS estimated_gph DOUBLE PRECISION",
    (
        "CREATE TABLE IF NOT EXISTS moisture_sensor ("
        " id TEXT PRIMARY KEY,"
        " label TEXT,"
        " tree_id BIGINT REFERENCES tree(tree_id) ON DELETE SET NULL,"
        " zone_id TEXT,"
        " created_at TIMESTAMPTZ NOT NULL DEFAULT now())"
    ),
    "CREATE INDEX IF NOT EXISTS idx_moisture_sensor_tree ON moisture_sensor (tree_id)",
    "CREATE INDEX IF NOT EXISTS idx_moisture_sensor_zone ON moisture_sensor (zone_id)",
    (
        "CREATE TABLE IF NOT EXISTS rainfall_forecast_log ("
        " for_date DATE PRIMARY KEY,"
        " forecast_1d_mm DOUBLE PRECISION, forecast_3d_mm DOUBLE PRECISION,"
        " forecast_5d_mm DOUBLE PRECISION,"
        " forecast_1d_at TIMESTAMPTZ, forecast_3d_at TIMESTAMPTZ,"
        " forecast_5d_at TIMESTAMPTZ,"
        " actual_nws_mm DOUBLE PRECISION, actual_gauge_mm DOUBLE PRECISION,"
        " actuals_at TIMESTAMPTZ,"
        " updated_at TIMESTAMPTZ NOT NULL DEFAULT now())"
    ),
    # Irrigation Phase 3: wetted area, zone/supervisor config, HITL proposals
    "ALTER TABLE tree ADD COLUMN IF NOT EXISTS wetted_area_m2 DOUBLE PRECISION",
    "ALTER TABLE tree DROP COLUMN IF EXISTS dripper_count",
    (
        "CREATE TABLE IF NOT EXISTS irrigation_zone_config ("
        " zone_id TEXT PRIMARY KEY,"
        " baseline_minutes INTEGER NOT NULL DEFAULT 20,"
        " supervised BOOLEAN NOT NULL DEFAULT true,"
        " updated_at TIMESTAMPTZ NOT NULL DEFAULT now())"
    ),
    "ALTER TABLE irrigation_zone_config DROP COLUMN IF EXISTS dripper_default",
    "ALTER TABLE irrigation_zone_config DROP COLUMN IF EXISTS baseline_frequency_days",
    (
        "CREATE TABLE IF NOT EXISTS irrigation_config ("
        " id INTEGER PRIMARY KEY DEFAULT 1 CHECK (id = 1),"
        " supervisor_frequency_hours INTEGER NOT NULL DEFAULT 24,"
        " auto_approve_skips BOOLEAN NOT NULL DEFAULT false,"
        " updated_at TIMESTAMPTZ NOT NULL DEFAULT now())"
    ),
    "INSERT INTO irrigation_config (id) VALUES (1) ON CONFLICT DO NOTHING",
    (
        "CREATE TABLE IF NOT EXISTS irrigation_proposal ("
        " thread_id TEXT PRIMARY KEY,"
        " zone_id TEXT NOT NULL,"
        " for_date DATE NOT NULL,"
        " status TEXT NOT NULL DEFAULT 'pending',"
        " action TEXT NOT NULL,"
        " summary TEXT NOT NULL DEFAULT '',"
        " payload JSONB NOT NULL DEFAULT '{}'::jsonb,"
        " result JSONB,"
        " created_at TIMESTAMPTZ NOT NULL DEFAULT now(),"
        " resolved_at TIMESTAMPTZ)"
    ),
    "CREATE INDEX IF NOT EXISTS idx_irrigation_proposal_status ON irrigation_proposal (status, created_at DESC)",
)


async def apply_startup_ddl(settings: Settings) -> None:
    async with get_engine(settings).begin() as conn:
        for stmt in _STARTUP_DDL:
            await conn.execute(text(stmt))
    _log.info("db.startup_ddl.applied", statements=len(_STARTUP_DDL))


async def healthcheck(settings: Settings) -> bool:
    """``SELECT 1`` against the pool - for the app's ``/health`` endpoint."""
    try:
        async with get_engine(settings).connect() as conn:
            await conn.execute(text("SELECT 1"))
        return True
    except Exception as exc:  # noqa: BLE001 - report, don't propagate
        _log.warning("db.healthcheck.failed", error=str(exc))
        return False


async def dispose_all() -> None:
    """Close every pooled connection across every cached engine."""
    for dsn, engine in list(_engines.items()):
        await engine.dispose()
        del _engines[dsn]
    _log.info("db.disposed")
