-- The one schema definition for the Orchard system. Runs once, on first
-- container start (empty data dir), as POSTGRES_USER against POSTGRES_DB.
-- tests/conftest.py re-applies this verbatim to the disposable orchard_test
-- database (every statement is IF NOT EXISTS / idempotent).
--
-- Identity PKs are GENERATED BY DEFAULT (not ALWAYS) so a caller MAY supply
-- an explicit id (e.g. TreeCreate.tree_id) and otherwise the sequence fills in.

-- ---------------------------------------------------------------------------
-- Extensions
-- ---------------------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS vector;          -- pgvector
CREATE EXTENSION IF NOT EXISTS pg_trgm;         -- trigram search on free text
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ---------------------------------------------------------------------------
-- Shared helpers
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ---------------------------------------------------------------------------
-- Core domain
-- ---------------------------------------------------------------------------
-- Zones are NOT stored here - they are the grower's Rachio irrigation zones,
-- read live and read-only (app/services/rachio.py). `tree.zone_id` is just a
-- free-text reference to a Rachio zone id.
CREATE TABLE IF NOT EXISTS tree (
    tree_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    species             TEXT NOT NULL,
    variety             TEXT NOT NULL,
    zone_id             TEXT,                      -- Rachio zone id (unvalidated)
    planted_date        DATE,                      -- age derived on read
    additional_context  TEXT,
    notes               TEXT,
    height_m            NUMERIC(4,2),              -- canopy scaling for the Care Plan engine
    canopy_spread_m     NUMERIC(4,2)               -- optional; defaults to 0.6 * height
);
-- idempotent for volumes created before the Care Plan engine
ALTER TABLE tree ADD COLUMN IF NOT EXISTS height_m NUMERIC(4,2);
ALTER TABLE tree ADD COLUMN IF NOT EXISTS canopy_spread_m NUMERIC(4,2);
CREATE INDEX IF NOT EXISTS idx_tree_zone ON tree (zone_id);

-- A routine care task for one tree. The Agronomist picks the task + a
-- rate_class; app/agent/care_plan.py scales estimated_minutes / resource_plan
-- deterministically from the tree's canopy volume. `required_resources` stays a
-- list[str] (Foreman-compatible); `resource_plan` carries the computed amounts.
CREATE TABLE IF NOT EXISTS task_templates (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tree_id             BIGINT NOT NULL REFERENCES tree(tree_id) ON DELETE CASCADE,
    name                TEXT NOT NULL,
    category            TEXT NOT NULL,             -- fertilize|mulch|prune|scout|spray|irrigation|weed|stake|soil_test|other
    rate_class          TEXT NOT NULL DEFAULT 'standard'
                            CHECK (rate_class IN ('light', 'standard', 'heavy')),
    interval_days       INTEGER NOT NULL CHECK (interval_days > 0),
    estimated_minutes   INTEGER NOT NULL CHECK (estimated_minutes > 0),
    priority_score      DOUBLE PRECISION NOT NULL DEFAULT 5.0,
    required_resources  JSONB NOT NULL DEFAULT '[]'::jsonb,   -- list[str]
    resource_plan       JSONB NOT NULL DEFAULT '[]'::jsonb,   -- list[{name, quantity, unit}]
    baseline_question   TEXT,                      -- "When was X last done?" (nullable)
    anchor_date         DATE,                      -- last known occurrence (from the baseline wizard)
    source_ids          JSONB NOT NULL DEFAULT '[]'::jsonb,   -- KB source ids the plan drew on
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_task_templates_tree ON task_templates (tree_id);

CREATE TABLE IF NOT EXISTS task (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tree_id             BIGINT NOT NULL REFERENCES tree(tree_id) ON DELETE CASCADE,
    template_id         BIGINT REFERENCES task_templates(id) ON DELETE SET NULL,
    action_type         TEXT NOT NULL,
    status              TEXT NOT NULL DEFAULT 'pending'
                            CHECK (status IN ('pending', 'completed', 'deferred', 'skipped')),
    priority_score      DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    scheduled_date      TIMESTAMPTZ,               -- NULL until scheduled
    frequency_days      INTEGER CHECK (frequency_days IS NULL OR frequency_days > 0),
    estimated_minutes   INTEGER CHECK (estimated_minutes IS NULL OR estimated_minutes > 0),
    required_resources  JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at        TIMESTAMPTZ
);
-- idempotent for volumes created before the Care Plan engine
ALTER TABLE task ADD COLUMN IF NOT EXISTS template_id BIGINT REFERENCES task_templates(id) ON DELETE SET NULL;
ALTER TABLE task DROP CONSTRAINT IF EXISTS task_status_check;
ALTER TABLE task ADD CONSTRAINT task_status_check
    CHECK (status IN ('pending', 'completed', 'deferred', 'skipped'));
CREATE INDEX IF NOT EXISTS idx_task_status_priority
    ON task (status, priority_score DESC);
CREATE INDEX IF NOT EXISTS idx_task_tree ON task (tree_id);
CREATE INDEX IF NOT EXISTS idx_task_template ON task (template_id) WHERE template_id IS NOT NULL;
-- pending queue, "due on or before" filter
CREATE INDEX IF NOT EXISTS idx_task_pending_sched
    ON task (scheduled_date) WHERE status = 'pending';

-- ---------------------------------------------------------------------------
-- Knowledge base (Consensus Fusion RAG)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sources (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         TEXT NOT NULL,
    source_type  TEXT NOT NULL CHECK (source_type IN ('file', 'text')),
    file_path    TEXT,
    raw_content  TEXT NOT NULL,
    upload_date  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS tree_sources (
    tree_id         BIGINT NOT NULL REFERENCES tree(tree_id) ON DELETE CASCADE,
    source_id       BIGINT NOT NULL REFERENCES sources(id)  ON DELETE CASCADE,
    priority_order  INT NOT NULL DEFAULT 0,   -- authority rank; 0 = highest
    PRIMARY KEY (tree_id, source_id)
);
-- idempotent for volumes created before priority ordering existed
ALTER TABLE tree_sources ADD COLUMN IF NOT EXISTS priority_order INT NOT NULL DEFAULT 0;
CREATE INDEX IF NOT EXISTS idx_tree_sources_source ON tree_sources (source_id);
CREATE INDEX IF NOT EXISTS idx_tree_sources_priority
    ON tree_sources (tree_id, priority_order);

-- Optional pgvector-native chunk store. The app currently keeps vectors in
-- ChromaDB; this table is the drop-in alternative (all-MiniLM-L6-v2 = 384 dims).
CREATE TABLE IF NOT EXISTS source_chunks (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id    BIGINT NOT NULL REFERENCES sources(id) ON DELETE CASCADE,
    chunk_index  INTEGER NOT NULL,
    content      TEXT NOT NULL,
    embedding    vector(384),
    UNIQUE (source_id, chunk_index)
);
CREATE INDEX IF NOT EXISTS idx_source_chunks_source ON source_chunks (source_id);
CREATE INDEX IF NOT EXISTS idx_source_chunks_embedding
    ON source_chunks USING hnsw (embedding vector_cosine_ops)
    WITH (m = 16, ef_construction = 64);

-- ---------------------------------------------------------------------------
-- Assistant chat history (Orchestrator)
-- ---------------------------------------------------------------------------
-- The Orchestrator graph is stateless - it gets the whole thread on every
-- request. These tables are the durable thread so a turn survives a page
-- reload / a different browser: the server loads history from here, runs the
-- turn, and appends the user message + the assistant's answer.
CREATE TABLE IF NOT EXISTS conversation (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       TEXT NOT NULL DEFAULT 'New conversation',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS chat_message (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id  BIGINT NOT NULL REFERENCES conversation(id) ON DELETE CASCADE,
    role             TEXT NOT NULL CHECK (role IN ('user', 'assistant')),
    content          TEXT NOT NULL DEFAULT '',
    meta             JSONB NOT NULL DEFAULT '{}'::jsonb,   -- route, tool_calls, redirect
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_chat_message_conversation
    ON chat_message (conversation_id, id);

-- ---------------------------------------------------------------------------
-- Planner-visible stats
-- ---------------------------------------------------------------------------
ANALYZE;
