-- The one schema definition for the Orchard system. Runs once, on first
-- container start (empty data dir), as POSTGRES_USER against POSTGRES_DB.
-- tests/conftest.py re-applies this verbatim to the disposable orchard_test
-- database (every statement is IF NOT EXISTS / idempotent).
--
-- Identity PKs are GENERATED BY DEFAULT (not ALWAYS) so a caller MAY supply
-- an explicit id (e.g. TreeCreate.tree_id) and otherwise the sequence fills in.

-- ---------------------------------------------------------------------------
-- Extensions
-- ---------------------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS vector;          -- pgvector
CREATE EXTENSION IF NOT EXISTS pg_trgm;         -- trigram search on free text
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ---------------------------------------------------------------------------
-- Shared helpers
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ---------------------------------------------------------------------------
-- Core domain
-- ---------------------------------------------------------------------------
-- Zones are NOT stored here - they are the grower's Rachio irrigation zones,
-- read live and read-only (app/services/rachio.py). `tree.zone_id` is just a
-- free-text reference to a Rachio zone id.
CREATE TABLE IF NOT EXISTS tree (
    tree_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    species             TEXT NOT NULL,
    variety             TEXT NOT NULL,
    zone_id             TEXT,                      -- Rachio zone id (unvalidated)
    planted_date        DATE,                      -- age derived on read
    additional_context  TEXT,
    notes               TEXT,
    height_m            NUMERIC(4,2),              -- canopy scaling for the Care Plan engine
    canopy_spread_m     NUMERIC(4,2),              -- optional; defaults to 0.6 * height
    estimated_gph       DOUBLE PRECISION,          -- whole-tree drip delivery, gallons/hour
    wetted_area_m2      DOUBLE PRECISION,          -- grower estimate of soil area the emitters wet
    expected_flowering_month SMALLINT CHECK (expected_flowering_month IS NULL OR (expected_flowering_month BETWEEN 1 AND 12)),
    expected_harvest_month   SMALLINT CHECK (expected_harvest_month IS NULL OR (expected_harvest_month BETWEEN 1 AND 12)),
    expected_dormancy_month  SMALLINT CHECK (expected_dormancy_month IS NULL OR (expected_dormancy_month BETWEEN 1 AND 12)),
    expected_flowering_months JSONB NOT NULL DEFAULT '[]'::jsonb,
    expected_harvest_months   JSONB NOT NULL DEFAULT '[]'::jsonb,
    expected_dormancy_months  JSONB NOT NULL DEFAULT '[]'::jsonb
);
-- idempotent for volumes created before the Care Plan / Irrigation engines
ALTER TABLE tree ADD COLUMN IF NOT EXISTS height_m NUMERIC(4,2);
ALTER TABLE tree ADD COLUMN IF NOT EXISTS canopy_spread_m NUMERIC(4,2);
ALTER TABLE tree ADD COLUMN IF NOT EXISTS estimated_gph DOUBLE PRECISION;    -- whole-tree gph
ALTER TABLE tree ADD COLUMN IF NOT EXISTS wetted_area_m2 DOUBLE PRECISION;   -- drip wetted area (Phase 3)
ALTER TABLE tree DROP COLUMN IF EXISTS dripper_count;                        -- removed: gph is whole-tree now
ALTER TABLE tree ADD COLUMN IF NOT EXISTS expected_flowering_month SMALLINT CHECK (expected_flowering_month IS NULL OR (expected_flowering_month BETWEEN 1 AND 12));
ALTER TABLE tree ADD COLUMN IF NOT EXISTS expected_harvest_month SMALLINT CHECK (expected_harvest_month IS NULL OR (expected_harvest_month BETWEEN 1 AND 12));
ALTER TABLE tree ADD COLUMN IF NOT EXISTS expected_dormancy_month SMALLINT CHECK (expected_dormancy_month IS NULL OR (expected_dormancy_month BETWEEN 1 AND 12));
ALTER TABLE tree ADD COLUMN IF NOT EXISTS expected_flowering_months JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE tree ADD COLUMN IF NOT EXISTS expected_harvest_months JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE tree ADD COLUMN IF NOT EXISTS expected_dormancy_months JSONB NOT NULL DEFAULT '[]'::jsonb;
UPDATE tree SET expected_flowering_months = jsonb_build_array(expected_flowering_month) WHERE expected_flowering_month IS NOT NULL AND (expected_flowering_months = '[]'::jsonb OR expected_flowering_months IS NULL);
UPDATE tree SET expected_harvest_months = jsonb_build_array(expected_harvest_month) WHERE expected_harvest_month IS NOT NULL AND (expected_harvest_months = '[]'::jsonb OR expected_harvest_months IS NULL);
UPDATE tree SET expected_dormancy_months = jsonb_build_array(expected_dormancy_month) WHERE expected_dormancy_month IS NOT NULL AND (expected_dormancy_months = '[]'::jsonb OR expected_dormancy_months IS NULL);
CREATE INDEX IF NOT EXISTS idx_tree_zone ON tree (zone_id);

-- A routine care task for one tree. The Agronomist picks the task + a
-- rate_class; app/agent/care_plan.py scales estimated_minutes / resource_plan
-- deterministically from the tree's canopy volume. `required_resources` stays a
-- list[str] (Foreman-compatible); `resource_plan` carries the computed amounts.
CREATE TABLE IF NOT EXISTS task_templates (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tree_id             BIGINT NOT NULL REFERENCES tree(tree_id) ON DELETE CASCADE,
    name                TEXT NOT NULL,
    category            TEXT NOT NULL,             -- fertilize|mulch|prune|scout|spray|irrigation|weed|stake|soil_test|other
    rate_class          TEXT NOT NULL DEFAULT 'standard'
                            CHECK (rate_class IN ('light', 'standard', 'heavy')),
    interval_days       INTEGER NOT NULL CHECK (interval_days > 0),
    estimated_minutes   INTEGER NOT NULL CHECK (estimated_minutes > 0),
    priority_score      DOUBLE PRECISION NOT NULL DEFAULT 5.0,
    required_resources  JSONB NOT NULL DEFAULT '[]'::jsonb,   -- list[str]
    resource_plan       JSONB NOT NULL DEFAULT '[]'::jsonb,   -- list[{name, quantity, unit}]
    baseline_question   TEXT,                      -- "When was X last done?" (nullable)
    anchor_date         DATE,                      -- last known occurrence (from the baseline wizard)
    source_ids          JSONB NOT NULL DEFAULT '[]'::jsonb,   -- KB source ids the plan drew on
    valid_months        JSONB NOT NULL DEFAULT '[]'::jsonb,   -- list[int] 1-12; [] = unconstrained
    biological_anchor   TEXT CHECK (biological_anchor IS NULL OR biological_anchor IN ('flowering', 'harvest', 'dormancy')),
    anchor_offset_days  INTEGER,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_task_templates_tree ON task_templates (tree_id);
ALTER TABLE task_templates ADD COLUMN IF NOT EXISTS valid_months JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE task_templates ADD COLUMN IF NOT EXISTS biological_anchor TEXT;
ALTER TABLE task_templates ADD COLUMN IF NOT EXISTS anchor_offset_days INTEGER;

CREATE TABLE IF NOT EXISTS task (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tree_id             BIGINT NOT NULL REFERENCES tree(tree_id) ON DELETE CASCADE,
    template_id         BIGINT REFERENCES task_templates(id) ON DELETE SET NULL,
    action_type         TEXT NOT NULL,
    status              TEXT NOT NULL DEFAULT 'pending'
                            CHECK (status IN ('pending', 'completed', 'deferred', 'skipped')),
    priority_score      DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    scheduled_date      TIMESTAMPTZ,               -- NULL until scheduled
    frequency_days      INTEGER CHECK (frequency_days IS NULL OR frequency_days > 0),
    estimated_minutes   INTEGER CHECK (estimated_minutes IS NULL OR estimated_minutes > 0),
    required_resources  JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at        TIMESTAMPTZ
);
-- idempotent for volumes created before the Care Plan engine
ALTER TABLE task ADD COLUMN IF NOT EXISTS template_id BIGINT REFERENCES task_templates(id) ON DELETE SET NULL;
ALTER TABLE task DROP CONSTRAINT IF EXISTS task_status_check;
ALTER TABLE task ADD CONSTRAINT task_status_check
    CHECK (status IN ('pending', 'completed', 'deferred', 'skipped'));
CREATE INDEX IF NOT EXISTS idx_task_status_priority
    ON task (status, priority_score DESC);
CREATE INDEX IF NOT EXISTS idx_task_tree ON task (tree_id);
CREATE INDEX IF NOT EXISTS idx_task_template ON task (template_id) WHERE template_id IS NOT NULL;
-- pending queue, "due on or before" filter
CREATE INDEX IF NOT EXISTS idx_task_pending_sched
    ON task (scheduled_date) WHERE status = 'pending';

-- ---------------------------------------------------------------------------
-- Knowledge base (Consensus Fusion RAG)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sources (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         TEXT NOT NULL,
    source_type  TEXT NOT NULL CHECK (source_type IN ('file', 'text')),
    file_path    TEXT,
    raw_content  TEXT NOT NULL,
    upload_date  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS tree_sources (
    tree_id         BIGINT NOT NULL REFERENCES tree(tree_id) ON DELETE CASCADE,
    source_id       BIGINT NOT NULL REFERENCES sources(id)  ON DELETE CASCADE,
    priority_order  INT NOT NULL DEFAULT 0,   -- authority rank; 0 = highest
    PRIMARY KEY (tree_id, source_id)
);
-- idempotent for volumes created before priority ordering existed
ALTER TABLE tree_sources ADD COLUMN IF NOT EXISTS priority_order INT NOT NULL DEFAULT 0;
CREATE INDEX IF NOT EXISTS idx_tree_sources_source ON tree_sources (source_id);
CREATE INDEX IF NOT EXISTS idx_tree_sources_priority
    ON tree_sources (tree_id, priority_order);

-- Optional pgvector-native chunk store. The app currently keeps vectors in
-- ChromaDB; this table is the drop-in alternative (all-MiniLM-L6-v2 = 384 dims).
CREATE TABLE IF NOT EXISTS source_chunks (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id    BIGINT NOT NULL REFERENCES sources(id) ON DELETE CASCADE,
    chunk_index  INTEGER NOT NULL,
    content      TEXT NOT NULL,
    embedding    vector(384),
    UNIQUE (source_id, chunk_index)
);
CREATE INDEX IF NOT EXISTS idx_source_chunks_source ON source_chunks (source_id);
CREATE INDEX IF NOT EXISTS idx_source_chunks_embedding
    ON source_chunks USING hnsw (embedding vector_cosine_ops)
    WITH (m = 16, ef_construction = 64);

-- ---------------------------------------------------------------------------
-- Assistant chat history (Orchestrator)
-- ---------------------------------------------------------------------------
-- The Orchestrator graph is stateless - it gets the whole thread on every
-- request. These tables are the durable thread so a turn survives a page
-- reload / a different browser: the server loads history from here, runs the
-- turn, and appends the user message + the assistant's answer.
CREATE TABLE IF NOT EXISTS conversation (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       TEXT NOT NULL DEFAULT 'New conversation',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS chat_message (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id  BIGINT NOT NULL REFERENCES conversation(id) ON DELETE CASCADE,
    role             TEXT NOT NULL CHECK (role IN ('user', 'assistant')),
    content          TEXT NOT NULL DEFAULT '',
    meta             JSONB NOT NULL DEFAULT '{}'::jsonb,   -- route, tool_calls, redirect
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_chat_message_conversation
    ON chat_message (conversation_id, id);

-- ---------------------------------------------------------------------------
-- Irrigation workflow (app/irrigation/) - Phase 1: sensor map + forecast log
-- ---------------------------------------------------------------------------
-- A physical moisture probe. May be tied to a specific tree, a Rachio zone, or
-- both (a zone probe that also sits at a representative tree). A tree's
-- effective reading = its own sensors, else its zone's sensors.
CREATE TABLE IF NOT EXISTS moisture_sensor (
    id          TEXT PRIMARY KEY,                 -- physical sensor id / UUID
    label       TEXT,
    tree_id     BIGINT REFERENCES tree(tree_id) ON DELETE SET NULL,
    zone_id     TEXT,                             -- Rachio zone id (unvalidated)
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_moisture_sensor_tree ON moisture_sensor (tree_id);
CREATE INDEX IF NOT EXISTS idx_moisture_sensor_zone ON moisture_sensor (zone_id);

-- One row per calendar day. Forecast columns are captured N days ahead (the
-- "roll" writes forecast_{1,3,5}d_mm for today+{1,3,5}); the actual columns are
-- backfilled the day after (observed NWS precip + the rain-bucket reading).
-- Lets us measure forecast error per horizon over time.
CREATE TABLE IF NOT EXISTS rainfall_forecast_log (
    for_date         DATE PRIMARY KEY,
    forecast_1d_mm   DOUBLE PRECISION,
    forecast_3d_mm   DOUBLE PRECISION,
    forecast_5d_mm   DOUBLE PRECISION,
    forecast_1d_at   TIMESTAMPTZ,
    forecast_3d_at   TIMESTAMPTZ,
    forecast_5d_at   TIMESTAMPTZ,
    actual_nws_mm    DOUBLE PRECISION,            -- observed (nearest NWS station)
    actual_gauge_mm  DOUBLE PRECISION,            -- observed (rain-bucket hardware)
    actuals_at       TIMESTAMPTZ,
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Phase 3: the baseline schedule a grower sets per zone (the "intended
-- baseline" - the stubbed tools log what they would push to Rachio).
CREATE TABLE IF NOT EXISTS irrigation_zone_config (
    zone_id                  TEXT PRIMARY KEY,
    baseline_minutes         INTEGER NOT NULL DEFAULT 20 CHECK (baseline_minutes >= 0),
    supervised               BOOLEAN NOT NULL DEFAULT true,
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT now()
);
ALTER TABLE irrigation_zone_config DROP COLUMN IF EXISTS dripper_default;

-- Singleton supervisor config.
CREATE TABLE IF NOT EXISTS irrigation_config (
    id                          INTEGER PRIMARY KEY DEFAULT 1 CHECK (id = 1),
    supervisor_frequency_hours  INTEGER NOT NULL DEFAULT 24 CHECK (supervisor_frequency_hours > 0),
    auto_approve_skips          BOOLEAN NOT NULL DEFAULT false,
    updated_at                  TIMESTAMPTZ NOT NULL DEFAULT now()
);
INSERT INTO irrigation_config (id) VALUES (1) ON CONFLICT DO NOTHING;

-- One row per supervisor deliberation (keyed by the LangGraph thread_id). The
-- graph pauses at `interrupt_before=["execute_rachio_action"]`; this row is the
-- HITL approval queue the UI reads.
CREATE TABLE IF NOT EXISTS irrigation_proposal (
    thread_id    TEXT PRIMARY KEY,
    zone_id      TEXT NOT NULL,
    for_date     DATE NOT NULL,
    status       TEXT NOT NULL DEFAULT 'pending'
                    CHECK (status IN ('pending', 'approved', 'rejected', 'executed', 'no_action', 'error')),
    action       TEXT NOT NULL,
    summary      TEXT NOT NULL DEFAULT '',
    payload      JSONB NOT NULL DEFAULT '{}'::jsonb,   -- decision + solution + water_balance
    result       JSONB,                                -- ToolResult, set on approval
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    resolved_at  TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_irrigation_proposal_status
    ON irrigation_proposal (status, created_at DESC);

-- ---------------------------------------------------------------------------
-- Planner-visible stats
-- ---------------------------------------------------------------------------
ANALYZE;
