-- The one schema definition for the Orchard system. Runs once, on first
-- container start (empty data dir), as POSTGRES_USER against POSTGRES_DB.
-- tests/conftest.py re-applies this verbatim to the disposable orchard_test
-- database (every statement is IF NOT EXISTS / idempotent).
--
-- Identity PKs are GENERATED BY DEFAULT (not ALWAYS) so a caller MAY supply
-- an explicit id (e.g. TreeCreate.tree_id) and otherwise the sequence fills in.

-- ---------------------------------------------------------------------------
-- Extensions
-- ---------------------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS vector;          -- pgvector
CREATE EXTENSION IF NOT EXISTS pg_trgm;         -- trigram search on free text
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ---------------------------------------------------------------------------
-- Shared helpers
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ---------------------------------------------------------------------------
-- Core domain
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS zone (
    zone_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           TEXT NOT NULL,
    soil_drainage  TEXT,                          -- free text
    water_source   TEXT                           -- free text
);

CREATE TABLE IF NOT EXISTS tree (
    tree_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    species             TEXT NOT NULL,
    variety             TEXT NOT NULL,
    zone_id             BIGINT REFERENCES zone(zone_id),  -- NO ACTION: deleting a
                                                            -- referenced zone raises
                                                            -- (service maps -> 409)
    planted_date        DATE,                      -- age derived on read
    additional_context  TEXT,
    notes               TEXT
);
CREATE INDEX IF NOT EXISTS idx_tree_zone ON tree (zone_id);

CREATE TABLE IF NOT EXISTS task (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tree_id             BIGINT NOT NULL REFERENCES tree(tree_id) ON DELETE CASCADE,
    action_type         TEXT NOT NULL,
    status              TEXT NOT NULL DEFAULT 'pending'
                            CHECK (status IN ('pending', 'completed', 'deferred')),
    priority_score      DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    scheduled_date      TIMESTAMPTZ,               -- NULL until scheduled
    frequency_days      INTEGER CHECK (frequency_days IS NULL OR frequency_days > 0),
    estimated_minutes   INTEGER CHECK (estimated_minutes IS NULL OR estimated_minutes > 0),
    required_resources  JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at        TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_task_status_priority
    ON task (status, priority_score DESC);
CREATE INDEX IF NOT EXISTS idx_task_tree ON task (tree_id);
-- pending queue, "due on or before" filter
CREATE INDEX IF NOT EXISTS idx_task_pending_sched
    ON task (scheduled_date) WHERE status = 'pending';

-- ---------------------------------------------------------------------------
-- Knowledge base (Consensus Fusion RAG)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sources (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         TEXT NOT NULL,
    source_type  TEXT NOT NULL CHECK (source_type IN ('file', 'text')),
    file_path    TEXT,
    raw_content  TEXT NOT NULL,
    upload_date  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS tree_sources (
    tree_id    BIGINT NOT NULL REFERENCES tree(tree_id) ON DELETE CASCADE,
    source_id  BIGINT NOT NULL REFERENCES sources(id)  ON DELETE CASCADE,
    PRIMARY KEY (tree_id, source_id)
);
CREATE INDEX IF NOT EXISTS idx_tree_sources_source ON tree_sources (source_id);

-- Optional pgvector-native chunk store. The app currently keeps vectors in
-- ChromaDB; this table is the drop-in alternative (all-MiniLM-L6-v2 = 384 dims).
CREATE TABLE IF NOT EXISTS source_chunks (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id    BIGINT NOT NULL REFERENCES sources(id) ON DELETE CASCADE,
    chunk_index  INTEGER NOT NULL,
    content      TEXT NOT NULL,
    embedding    vector(384),
    UNIQUE (source_id, chunk_index)
);
CREATE INDEX IF NOT EXISTS idx_source_chunks_source ON source_chunks (source_id);
CREATE INDEX IF NOT EXISTS idx_source_chunks_embedding
    ON source_chunks USING hnsw (embedding vector_cosine_ops)
    WITH (m = 16, ef_construction = 64);

-- ---------------------------------------------------------------------------
-- Planner-visible stats
-- ---------------------------------------------------------------------------
ANALYZE;
